### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yansal** [yansal/challenge#1]
# Required
- [x] Authentication for POST /tasks/
- [x] PATCH /tasks/:id
- [x] Embed user in task & comment resources
- [x] Add auto updated_at column in tasks table
- [x] Add progression column in tasks table
- [x] Sort by creation date
# Bonus
- [ ] Add Pagination
- [ ] Implement threaded comments like reddit
- [ ] Implement moderators for each tasks, a moderator is able to delete a comment
